config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  resources :categories

  root 'tasks#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Task, owner_id: user.id
    can :read, Task, participating_users: { user_id: user.id}
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :bigint           not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Category < ApplicationRecord
  has_many :tasks
  validates :name, :description, presence: true
  validates :name, uniqueness: {case_sensitive: false}
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :bigint           not null, primary key
#  name        :string
#  description :text
#  due_date    :date
#  category_id :bigint           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Task < ApplicationRecord
  belongs_to :category
  belongs_to :owner, class_name: 'User'
  has_many :participating_users, class_name: 'Participant'
  has_many :participants, through: :participating_users, source: :user

  validates :participating_users, presence: true
  validates :name, :description, :due_date, presence: true
  validates :name, uniqueness: {case_sensitive: false}
  validate :due_date_validity

  before_create :create_code
  after_create :send_email

  accepts_nested_attributes_for :participating_users, allow_destroy: true

  def due_date_validity
    return if due_date.blank?
    return if due_date > Date.today
    errors.add :due_date, I18n.t('tasks.errors.invalid_due_date')
  end

  def create_code
    self.code = "#{owner_id}#{Time.now.to_i.to_s(36)}#{SecureRandom.hex(8)}"
  end

  def send_email
    [participants + [owner]].each do |user|
      ParticipantMailer.with(user: user, task: self).new_task_email.deliver!
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :owned_tasks, class_name: 'Task', foreign_key: 'owner_id'
  has_many :participations, class_name: 'Participant'
  has_many :tasks, through: :participations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_locale

  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path
  end

  def set_locale
    I18n.locale = 'es'
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.joins(:participants).where(
      'owner_id = ? OR participants.user_id = ?',
      current_user.id,
      current_user.id
    ).group(:id)
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @task.participating_users.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    # Devise logged in user
    @task.owner = current_user
    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(
        :name,
        :description,
        :due_date,
        :category_id,
        participating_users_attributes: [
          :user_id,
          :role,
          :id,
          :_destroy
        ]
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@category) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name, label: t('.name')
    = f.input :description, label: t('.description')

  .form-actions
    = f.button :submit

app/views/categories/edit.html.haml
%h1= t('editing_category')

= render 'form'

= link_to t('common.edit'), @category
\|
= link_to t('common.back'), categories_path

app/views/categories/index.html.haml
%h1= t('.title')

%table
  %thead
    %tr
      %th= t('categories.model.name')
      %th= t('categories.model.description')
      %th
      %th
      %th

  %tbody
    - @categories.each do |category|
      %tr
        %td= category.name
        %td= category.description
        %td= link_to t('common.show'), category
        %td= link_to t('common.edit'), edit_category_path(category)
        %td= link_to t('common.destroy'), category, :method => :delete, :data => { :confirm => t('common.sure') }

%br

= link_to t('categories.new.categories.new_category'), new_category_path

app/views/categories/new.html.haml
%h1= t('.categories.new_category')

= render 'form'

= link_to t('common.back'), categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b= t('categories.model.name')
  = @category.name
%p
  %b= t('categories.model.description')
  = @category.description

= link_to t('common.edit'), edit_category_path(@category)
\|
= link_to t('common.back'), categories_path

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
  %br
  %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
    %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navbar.html.haml
-# app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark-blue
  %a.navbar-brand
    = image_tag 'logo.jpg', class: 'd-inline-block align-top', width: 85
  %button.navbar-toggler{"aria-controls" => "navbarNavDropdown", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavDropdown", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarNavDropdown.collapse.navbar-collapse
    %ul.navbar-nav
      %li.nav-item.active
        %a.nav-link{:href => root_path}
          Inicio
          %span.sr-only (current)
      %li.nav-item
        %a.nav-link{ href: categories_path } Categorías
  = link_to 'Crear Tarea', new_task_path, class: 'btn btn-light ml-2'
  .dropdown.dropdown-user
    %a#userMenu{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown"}
      = image_tag "https://robohash.org/#{current_user.email}?size=38x38"
    .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "userMenu"}
      .dropdown-item.small.text-right= current_user.email
      .dropdown-divider
      = link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do
        .fas.fa-sign-out
        Cerrar sesión

app/views/layouts/application.html.haml
-# frozen_string_literal: true
-# app/views/layouts/application.html.haml
!!!
%html
%head
%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
%title Task Manager
= csrf_meta_tags
= csp_meta_tag
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
%body
  = render 'layouts/navbar'
  .container.mt-4.pb-4
    .main-flash-messages
      = render 'layouts/messages'
    = yield

app/views/tasks/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@task) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  .form-inputs
    = f.input :name, label: t('.name')
    = f.input :description, label: t('.description')
    = f.input :due_date, label: t('.due_date')
    = f.association :category, label: t('.category')
    #addParticipants
      = link_to_add_association f,
                              :participating_users,
                              'data-association-insertion-node' => '.participants .participant-container',
                              'data-turbolinks' => false do
        = t('.add-participant')
    .participants
      = f.simple_fields_for :participating_users do |g|
        = render partial: 'participating_user_fields', locals: {f:g}
        .participant-container

  .form-actions
    = f.button :submit

app/views/tasks/_participating_user_fields.html.haml
.nested_fields
   = f.input :user_id, as: :select, collection: User.all - [current_user]
   = f.input :role

app/views/tasks/edit.html.haml
%h1= t('editing_task')

= render 'form'

= link_to t('common.show'), @task
\|
= link_to t('common.back'), tasks_path

app/views/tasks/index.html.haml
%h1=t('.title')

%table
  %thead
    %tr
      %th=t('.name')
      %th=t('.description')
      %th=t('.due_date')
      %th=t('category')
      %th
      %th
      %th

  %tbody
    - @tasks.each do |task|
      %tr
        %td= task.name
        %td= task.description
        %td= task.due_date
        %td= task.category
        %td= link_to t('common.show'), task
        %td= link_to t('common.edit'), edit_task_path(task)
        %td= link_to t('common.destroy'), task, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to t('.new_task'), new_task_path

app/views/tasks/new.html.haml
%h1=t('.title')

= render 'form'

= link_to t('common.back'), tasks_path

app/views/tasks/show.html.haml
%p#notice= notice

%p
  %b= "#{t('tasks.model.name')}:"
  = @task.name
%p
  %b "#{t('tasks.model.description')}:"
  = @task.description
%p
  %b "#{t('tasks.model.due_date')}:"
  = @task.due_date
%p
  %b "#{t('tasks.model.category')}:"
  = @task.category

= link_to t('common.edit'), edit_task_path(@task)
\|
= link_to t('common.back'), tasks_path